//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intranet_noticias
    {
        public int num_folio { get; set; }
        public string titulo { get; set; }
        public string noticia { get; set; }
        public string resumen { get; set; }
        public System.DateTime fecha { get; set; }
        public string imagenUrl { get; set; }
        public string autor { get; set; }
    }
}
